kind: Service
apiVersion: v1
metadata:
  name: servicio-docker-prueba-service
spec:
  type: LoadBalancer
  selector:
    app: servicio-docker-prueba
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
